# Generated by Django 5.2.4 on 2025-07-07 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='contect',
            new_name='content',
        ),
    ]
